"""Make some movie fields nullable

Revision ID: 534f9202b700
Revises: 64653526138a
Create Date: 2025-09-22 10:48:02.717021

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "534f9202b700"
down_revision: str | Sequence[str] | None = "64653526138a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("movie", "release_year", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("movie", "director_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("movie", "director_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("movie", "release_year", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
