"""Create initial tables

Revision ID: 64653526138a
Revises: 6201657db2dd
Create Date: 2025-09-11 15:53:07.129075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64653526138a'
down_revision: Union[str, Sequence[str], None] = '6201657db2dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('director',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_director_name'), 'director', ['name'], unique=False)
    op.create_index(op.f('ix_director_uuid'), 'director', ['uuid'], unique=True)
    op.create_table('genre',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_genre_name'), 'genre', ['name'], unique=True)
    op.create_index(op.f('ix_genre_uuid'), 'genre', ['uuid'], unique=True)
    op.create_table('movie',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=False),
    sa.Column('director_id', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['director_id'], ['director.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_movie_title'), 'movie', ['title'], unique=False)
    op.create_index(op.f('ix_movie_uuid'), 'movie', ['uuid'], unique=True)
    op.create_table('moviegenreassociation',
    sa.Column('movie_id', sa.UUID(), nullable=False),
    sa.Column('genre_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moviegenreassociation')
    op.drop_index(op.f('ix_movie_uuid'), table_name='movie')
    op.drop_index(op.f('ix_movie_title'), table_name='movie')
    op.drop_table('movie')
    op.drop_index(op.f('ix_genre_uuid'), table_name='genre')
    op.drop_index(op.f('ix_genre_name'), table_name='genre')
    op.drop_table('genre')
    op.drop_index(op.f('ix_director_uuid'), table_name='director')
    op.drop_index(op.f('ix_director_name'), table_name='director')
    op.drop_table('director')
    # ### end Alembic commands ###
